### PR TITLE
Fix issue 88

### PR DESCRIPTION
**Pull request by londumas**
fix issue 88,
i.e. remove mean_delta vs. lambda_obs
https://github.com/igmhub/pyLyA/issues/88

### CODE REVIEW

**Comment by ngbusca** [comment]
I agree that we need this fix, but maybe the code that does it could be more compact. Let me think about how to improve it

**Comment by londumas** [comment]
seems compact to me, it only calls a method then remove the delta.
but if you find better, why not.

**Comment by londumas** [comment]
any idea what could be changed ?

**Comment by londumas** [comment]
@ngbusca could you take care of what we said last thursday ?
Or we could apply this merge and make it more beautiful another time

**Pull request merged**
