### PR TITLE
Fix issue 77

### PR DESCRIPTION
**Pull request by londumas**
https://github.com/igmhub/pyLyA/issues/77

io.py doesn't work with new pix format

### CODE REVIEW

**Comment by ngbusca** [comment]
What is this PR fixing?

**Comment by londumas** [comment]
I don't understand what "PR" means ?
the merge request fix reading the new pixel format

**Comment by ngbusca** [comment]
PR = pull request. Ok, the message says "fix fluxcalib again."

Please @slosar can you review the changes?

**Comment by londumas** [comment]
yes @ngbusca sory for the commit comment.
Anyway, the title is fix issue 77

**Comment by londumas** [comment]
I have tested it and it works well, but it is better if @slosar reveiws it

**Comment by ngbusca** [comment]
I'm working on this now to speed up the input time

**Comment by londumas** [comment]
The nside is now read directly from the master.ftis file that has to be in the same folder as the pixs files.

**Comment by ngbusca** [comment]
I've just pushed some changes to speed up the reading time. @londumas can you try? I'm getting ~1 msec per spectrum, so about three minutes to read the entire data sample.

**Comment by ngbusca** [comment]
@londumas if this works ok on your side I'll merge

**Comment by londumas** [comment]
ok I will try @ngbusca

**Comment by londumas** [comment]
It works and is way faster, thank you @ngbusca

**Pull request merged**
