### PR TITLE
fix issue 51

### PR DESCRIPTION
**Pull request by londumas**
definition of eta is inverse of papers

### CODE REVIEW

**Comment by ngbusca** [comment]
why do you want to change this? It was done on purpose.

**Comment by londumas** [comment]
why was it done on purpose ?
Why change the definition of eta ?

**Comment by ngbusca** [comment]
it's directly the slope of the fit sigma_forest vs 1/ivar.

**Comment by londumas** [comment]
yes I understand that but why not call it iveta in the code and in the HDU ?

**Comment by londumas** [comment]
sory ieta

**Comment by ngbusca** [comment]
I don't see a point of changing this.

**Comment by londumas** [comment]
This is just that then we have output that differ from precedent papers.
But this change nothing to the BAO obviously.
At the end it is your call

**Comment by andreufont** [comment]
I'd just add a comment in the code saying
# this definition is the inverse of the one used in paper xxx

**Comment by ngbusca** [comment]
I don't think it even makes sense to discuss this.

**Pull request closed without merging**
